import { PostMeta } from '@/types';

export const postsMeta: PostMeta[] = [
  {
    title: '컴퓨터는 0.1을 모른다',
    path: '/post/floatingpoint',
    slug: 'floatingpoint',
    summary: '무한한 수를 유한한 비트에 구겨 넣으려다 생긴 일',
    category: 'CS',
    date: '2025.08',
    order: 1,
  },
  {
    title: '손가락이 10개라서 십진법, 전기가 두 갈래라서 이진법',
    path: '/post/binary',
    slug: 'binary',
    summary: '컴퓨터가 0과 1만 쓰는 건 전기의 본성이 그렇기 때문이다',
    category: 'CS',
    date: '2025.08',
    order: 2,
  },
  {
    title: '7 + 5 = 12가 나오기까지',
    path: '/post/calculator',
    slug: 'calculator',
    summary: '계산기 안에는 컴퓨터 구조 교과서가 통째로 들어 있다',
    category: 'CS',
    date: '2025.08',
    order: 3,
  },
  {
    slug: 'nft',
    title: '우클릭으로 저장되는 그림이 900억 원인 이유',
    path: '/post/nft',
    summary: 'NFT 시장은 거품이어도, 그 아래 기술은 다른 이야기다',
    category: 'Blockchain',
    date: '2025.08',
  },
  {
    title: 'KTX 자동 예매가 어느 날 갑자기 먹통이 됐다',
    path: '/post/korailReserve',
    slug: 'korailReserve',
    summary:
      '리뉴얼된 코레일 홈페이지에 대응하며 Selenium 코드를 전면 재작성한 기록',
    category: 'Dev',
    date: '2025.08',
  },
  {
    title: '블록체인에는 Ctrl+Z가 없다',
    path: '/post/immutability',
    slug: 'immutability',
    summary: '한 글자 바꾸면 해시가 달라지고, 그 뒤 모든 블록이 무너진다',
    category: 'Blockchain',
    date: '2025.08',
  },
  {
    title: '서버가 거짓말을 한다면',
    path: '/post/trust-your-server',
    slug: 'trust-your-server',
    summary:
      'SK텔레콤 해킹을 보며 든 생각 — 신뢰를 사람에게 맡기면 무슨 일이 생기나',
    category: 'Blockchain',
    date: '2025.08',
  },
  {
    title: '같은 코드인데 Go는 통과, JS는 시간초과',
    path: '/post/languagePerformance',
    slug: 'languagePerformance',
    summary: '알고리즘이 맞아도 언어 선택이 결과를 바꾼다',
    category: 'Dev',
    date: '2025.08',
  },
  {
    title: '팀마다 Node.js 버전이 다른 데는 이유가 있었다',
    path: '/post/nodeVersion',
    slug: 'nodeVersion',
    summary: '최신 버전이 항상 좋은 게 아닌 이유',
    category: 'Dev',
    date: '2025.08',
  },
  {
    title: 'API 문서가 항상 틀려있던 이유',
    path: '/post/FastifySwagger',
    slug: 'FastifySwagger',
    summary: '코드는 바뀌는데 문서는 그대로인 문제를 Swagger로 해결한 과정',
    category: 'Dev',
    date: '2025.08',
  },
  {
    title: 'MetaMask가 브라우저에 꽂아둔 전용선',
    path: '/post/windowEthereum',
    slug: 'windowEthereum',
    summary: 'window.ethereum은 크롬이 준 것도, 내가 만든 것도 아니다',
    category: 'Blockchain',
    date: '2025.08',
  },
  {
    title: '어제 접속됐던 서버가 오늘 막힌 이유',
    path: '/post/dhcp',
    slug: 'dhcp',
    summary: 'IP가 바뀐 건 네트워크가 고장난 게 아니라 설계대로 작동한 것이다',
    category: 'Dev',
    date: '2025.11',
  },
  {
    title: 'NAT Gateway가 한 달에 32달러 나왔다',
    path: '/post/NATInstance',
    slug: 'NATInstance',
    summary: '트래픽도 없는데 왜 이렇게 나오지 — 구조를 뜯어보니 답이 있었다',
    category: 'Dev',
    date: '2025.12',
  },
  {
    title: 'Claude가 이미 아는 내용을 왜 스킬로 넣지?',
    path: '/post/eccOpensource',
    slug: 'eccOpensource',
    summary:
      'ECC 오픈소스에 기여하면서 깨달은, AI 시대에 진짜 가치 있는 문서의 조건',
    category: 'Dev',
    date: '2026.05',
  },
  {
    title: '자리를 비운 사이 서비스가 더 단단해지는 법',
    path: '/post/hardening',
    slug: 'hardening',
    summary:
      '레드팀이 공격하고 블루팀이 막는 사이클을 Claude 커맨드로 자동화한 이야기',
    category: 'Dev',
    date: '2026.06',
  },
  {
    title: '1일차 (VPC, Subnet, Route Table)',
    path: '/post/ncpNetwork',
    slug: 'ncpNetwork',
    summary: '서버를 만들기 전에 길부터 깔았다 — VPC와 Subnet, Route Table, NAT Gateway, VPC Peering',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
  {
    title: '2일차 (NACL, ACG, Prometheus)',
    path: '/post/naclAcg',
    slug: 'naclAcg',
    summary:
      'NACL은 Stateless, ACG는 Stateful — 아웃바운드를 안 열어서 SSH가 막힌 날',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
  {
    title: '3일차 (Docker 네트워크, Overlay)',
    path: '/post/dockerNetwork',
    slug: 'dockerNetwork',
    summary:
      '컨테이너가 둘이 되면 이름이 필요하고, 호스트가 둘이 되면 터널이 필요하다',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
  {
    title: '4일차 (K3s, Server와 Agent)',
    path: '/post/k3sAgentJoin',
    slug: 'k3sAgentJoin',
    summary: 'K3S_URL 하나로 server와 agent가 갈린다 — 옵션을 빼먹고 클러스터를 두 개 만든 날',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
  {
    title: '네이버 클라우드 심화 과정 회고',
    path: '/post/ncpProfessional',
    slug: 'ncpProfessional',
    summary:
      '네트워크부터 관리형 쿠버네티스까지, 6일 과정을 일차별로 정리한 목차',
    category: 'Dev',
    date: '2026.08',
  },
  {
    title: '5일차 (Deployment, Service, Label)',
    path: '/post/k8sManifest',
    slug: 'k8sManifest',
    summary:
      'Deployment와 Service를 잇는 건 Label 문자열 하나뿐이다. 여기서 틀리면 조용히 틀린다',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
  {
    title: '6일차 (NodePort, Ingress, NKS, HPA)',
    path: '/post/k8sToNks',
    slug: 'k8sToNks',
    summary:
      '직접 만들던 것을 관리형 쿠버네티스에 넘겼다 — NodePort와 Ingress부터 ALB, HPA, 무중단 배포까지',
    category: 'Dev',
    date: '2026.08',
    listed: false,
  },
];
