// 네이버 클라우드 "서비스 아이콘 및 활용예시" PPTX에서 뽑은 아이콘 목록.
// 직접 고치지 말고 docs/studio/build_icons.py로 다시 만든다.

export type StudioIcon = {
  id: string;
  name: string;
  category: string;
  src: string;
};

export const ICONS: readonly StudioIcon[] = [
  {
    id: 'application-server-launcher',
    name: 'Application Server Launcher',
    category: 'Compute',
    src: '/studio/icons/application-server-launcher.png',
  },
  {
    id: 'auto-scaling',
    name: 'Auto Scaling',
    category: 'Compute',
    src: '/studio/icons/auto-scaling.png',
  },
  {
    id: 'bare-metal-server',
    name: 'Bare Metal Server',
    category: 'Compute',
    src: '/studio/icons/bare-metal-server.png',
  },
  {
    id: 'cloud-functions',
    name: 'Cloud Functions',
    category: 'Compute',
    src: '/studio/icons/cloud-functions.png',
  },
  {
    id: 'gpu-server',
    name: 'GPU Server',
    category: 'Compute',
    src: '/studio/icons/gpu-server.png',
  },
  {
    id: 'hpc',
    name: 'HPC',
    category: 'Compute',
    src: '/studio/icons/hpc.png',
  },
  {
    id: 'server',
    name: 'Server',
    category: 'Compute',
    src: '/studio/icons/server.png',
  },
  {
    id: 'server-compact',
    name: 'Server/Compact',
    category: 'Compute',
    src: '/studio/icons/server-compact.png',
  },
  {
    id: 'server-high-memory',
    name: 'Server/High-Memory',
    category: 'Compute',
    src: '/studio/icons/server-high-memory.png',
  },
  {
    id: 'server-micro',
    name: 'Server/Micro',
    category: 'Compute',
    src: '/studio/icons/server-micro.png',
  },
  {
    id: 'ssd-server',
    name: 'SSD Server',
    category: 'Compute',
    src: '/studio/icons/ssd-server.png',
  },
  {
    id: 'virtual-dedicatedserver',
    name: 'Virtual DedicatedServer',
    category: 'Compute',
    src: '/studio/icons/virtual-dedicatedserver.png',
  },
  {
    id: 'high-cpuserver',
    name: 'High CPUServer',
    category: 'Compute',
    src: '/studio/icons/high-cpuserver.png',
  },
  {
    id: 'virtual-pc',
    name: 'Virtual PC',
    category: 'Compute',
    src: '/studio/icons/virtual-pc.png',
  },
  {
    id: 'cpu-intensive',
    name: 'CPU Intensive',
    category: 'Compute',
    src: '/studio/icons/cpu-intensive.png',
  },
  {
    id: 'kubernetes-service',
    name: 'Kubernetes Service',
    category: 'Containers',
    src: '/studio/icons/kubernetes-service.png',
  },
  {
    id: 'ncloud-containerregistry',
    name: 'Ncloud ContainerRegistry',
    category: 'Containers',
    src: '/studio/icons/ncloud-containerregistry.png',
  },
  {
    id: 'archive-storage',
    name: 'Archive Storage',
    category: 'Storage',
    src: '/studio/icons/archive-storage.png',
  },
  {
    id: 'backup',
    name: 'Backup',
    category: 'Storage',
    src: '/studio/icons/backup.png',
  },
  {
    id: 'block-storage',
    name: 'Block Storage',
    category: 'Storage',
    src: '/studio/icons/block-storage.png',
  },
  {
    id: 'file-storage',
    name: 'File Storage',
    category: 'Storage',
    src: '/studio/icons/file-storage.png',
  },
  {
    id: 'nas',
    name: 'NAS',
    category: 'Storage',
    src: '/studio/icons/nas.png',
  },
  {
    id: 'object-storage',
    name: 'Object Storage',
    category: 'Storage',
    src: '/studio/icons/object-storage.png',
  },
  {
    id: 'object-storage-worm',
    name: 'Object Storage- WORM',
    category: 'Storage',
    src: '/studio/icons/object-storage-worm.png',
  },
  {
    id: 'ncloud-storage',
    name: 'Ncloud Storage',
    category: 'Storage',
    src: '/studio/icons/ncloud-storage.png',
  },
  {
    id: 'cloud-connect',
    name: 'Cloud Connect',
    category: 'Networking',
    src: '/studio/icons/cloud-connect.png',
  },
  {
    id: 'global-internetservice',
    name: 'Global InternetService',
    category: 'Networking',
    src: '/studio/icons/global-internetservice.png',
  },
  {
    id: 'global-routemanager',
    name: 'Global RouteManager',
    category: 'Networking',
    src: '/studio/icons/global-routemanager.png',
  },
  {
    id: 'global-trafficmanager',
    name: 'Global TrafficManager',
    category: 'Networking',
    src: '/studio/icons/global-trafficmanager.png',
  },
  {
    id: 'managed-ipsec-vpn',
    name: 'Managed IPsec VPN',
    category: 'Networking',
    src: '/studio/icons/managed-ipsec-vpn.png',
  },
  {
    id: 'load-balancer',
    name: 'Load Balancer',
    category: 'Networking',
    src: '/studio/icons/load-balancer.png',
  },
  {
    id: 'nat-gateway',
    name: 'NAT Gateway',
    category: 'Networking',
    src: '/studio/icons/nat-gateway.png',
  },
  {
    id: 'vpc-peering',
    name: 'VPC Peering',
    category: 'Networking',
    src: '/studio/icons/vpc-peering.png',
  },
  {
    id: 'global-dns',
    name: 'Global DNS',
    category: 'Networking',
    src: '/studio/icons/global-dns.png',
  },
  {
    id: 'network-load-balancer',
    name: 'Network Load Balancer',
    category: 'Networking',
    src: '/studio/icons/network-load-balancer.png',
  },
  {
    id: 'network-proxy-load-balancer',
    name: 'Network Proxy Load Balancer',
    category: 'Networking',
    src: '/studio/icons/network-proxy-load-balancer.png',
  },
  {
    id: 'application-load-balancer',
    name: 'Application Load Balancer',
    category: 'Networking',
    src: '/studio/icons/application-load-balancer.png',
  },
  {
    id: 'classic-path',
    name: 'Classic Path',
    category: 'Networking',
    src: '/studio/icons/classic-path.png',
  },
  {
    id: 'vpc-virtual-private-cloud',
    name: 'VPC(Virtual Private Cloud)',
    category: 'Networking',
    src: '/studio/icons/vpc-virtual-private-cloud.png',
  },
  {
    id: 'cubrid',
    name: 'CUBRID',
    category: 'Database',
    src: '/studio/icons/cubrid.png',
  },
  {
    id: 'cloud-db-for-redis',
    name: 'Cloud DB for Redis',
    category: 'Database',
    src: '/studio/icons/cloud-db-for-redis.png',
  },
  {
    id: 'cloud-dbfor-redis',
    name: 'Cloud DBfor Redis',
    category: 'Database',
    src: '/studio/icons/cloud-dbfor-redis.png',
  },
  {
    id: 'cloud-db',
    name: 'Cloud DB',
    category: 'Database',
    src: '/studio/icons/cloud-db.png',
  },
  {
    id: 'cloud-db-mssql',
    name: 'Cloud DB(MSSQL)',
    category: 'Database',
    src: '/studio/icons/cloud-db-mssql.png',
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    category: 'Database',
    src: '/studio/icons/mariadb.png',
  },
  {
    id: 'experdb',
    name: 'eXperDB',
    category: 'Database',
    src: '/studio/icons/experdb.png',
  },
  {
    id: 'cloud-db-for-mssql',
    name: 'Cloud DB for MSSQL',
    category: 'Database',
    src: '/studio/icons/cloud-db-for-mssql.png',
  },
  {
    id: 'cloud-db-for-mysql',
    name: 'Cloud DB for MySQL',
    category: 'Database',
    src: '/studio/icons/cloud-db-for-mysql.png',
  },
  {
    id: 'cloud-db-for-postgresql',
    name: 'Cloud DB for PostgreSQL',
    category: 'Database',
    src: '/studio/icons/cloud-db-for-postgresql.png',
  },
  {
    id: 'cloud-dbfor-mongodb',
    name: 'Cloud DBfor MongoDB',
    category: 'Database',
    src: '/studio/icons/cloud-dbfor-mongodb.png',
  },
  {
    id: 'cloud-dbfor-postgresql',
    name: 'Cloud DBfor PostgreSQL',
    category: 'Database',
    src: '/studio/icons/cloud-dbfor-postgresql.png',
  },
  {
    id: 'tibero',
    name: 'Tibero',
    category: 'Database',
    src: '/studio/icons/tibero.png',
  },
  {
    id: 'databasemigration-service',
    name: 'DatabaseMigration Service',
    category: 'Database',
    src: '/studio/icons/databasemigration-service.png',
  },
  {
    id: 'acg',
    name: 'ACG',
    category: 'Security',
    src: '/studio/icons/acg.png',
  },
  {
    id: 'acl',
    name: 'ACL',
    category: 'Security',
    src: '/studio/icons/acl.png',
  },
  {
    id: 'app-safer',
    name: 'App Safer',
    category: 'Security',
    src: '/studio/icons/app-safer.png',
  },
  {
    id: 'app-security-checker',
    name: 'App Security Checker',
    category: 'Security',
    src: '/studio/icons/app-security-checker.png',
  },
  {
    id: 'basic-security',
    name: 'Basic Security',
    category: 'Security',
    src: '/studio/icons/basic-security.png',
  },
  {
    id: 'certificate-manager',
    name: 'Certificate Manager',
    category: 'Security',
    src: '/studio/icons/certificate-manager.png',
  },
  {
    id: 'cloudsecurity-watcher',
    name: 'CloudSecurity Watcher',
    category: 'Security',
    src: '/studio/icons/cloudsecurity-watcher.png',
  },
  {
    id: 'complianceguide',
    name: 'ComplianceGuide',
    category: 'Security',
    src: '/studio/icons/complianceguide.png',
  },
  {
    id: 'file-safer',
    name: 'File Safer',
    category: 'Security',
    src: '/studio/icons/file-safer.png',
  },
  {
    id: 'hardware-security-module-hsm',
    name: 'Hardware Security Module(HSM)',
    category: 'Security',
    src: '/studio/icons/hardware-security-module-hsm.png',
  },
  {
    id: 'pca-private-ca',
    name: 'PCA (Private CA)',
    category: 'Security',
    src: '/studio/icons/pca-private-ca.png',
  },
  {
    id: 'secret-manager',
    name: 'Secret Manager',
    category: 'Security',
    src: '/studio/icons/secret-manager.png',
  },
  {
    id: 'secure-zone',
    name: 'Secure Zone',
    category: 'Security',
    src: '/studio/icons/secure-zone.png',
  },
  {
    id: 'securitymonitoring',
    name: 'SecurityMonitoring',
    category: 'Security',
    src: '/studio/icons/securitymonitoring.png',
  },
  {
    id: 'system-security-checker',
    name: 'System Security Checker',
    category: 'Security',
    src: '/studio/icons/system-security-checker.png',
  },
  {
    id: 'web-security-checker',
    name: 'Web Security Checker',
    category: 'Security',
    src: '/studio/icons/web-security-checker.png',
  },
  {
    id: 'webshell-behavior-detector',
    name: 'Webshell Behavior Detector',
    category: 'Security',
    src: '/studio/icons/webshell-behavior-detector.png',
  },
  {
    id: 'ssl-vpn',
    name: 'SSL VPN',
    category: 'Security',
    src: '/studio/icons/ssl-vpn.png',
  },
  {
    id: 'key-managementservice',
    name: 'Key ManagementService',
    category: 'Security',
    src: '/studio/icons/key-managementservice.png',
  },
  {
    id: 'secure-access',
    name: 'Secure Access',
    category: 'Security',
    src: '/studio/icons/secure-access.png',
  },
  {
    id: 'ncloud-tensorflowserver',
    name: 'Ncloud TensorFlowServer',
    category: 'AI Services',
    src: '/studio/icons/ncloud-tensorflowserver.png',
  },
  {
    id: 'ncloud-tensorflowcluster',
    name: 'Ncloud TensorFlowCluster',
    category: 'AI Services',
    src: '/studio/icons/ncloud-tensorflowcluster.png',
  },
  {
    id: 'clova-chatbot',
    name: 'CLOVA Chatbot',
    category: 'AI Services',
    src: '/studio/icons/clova-chatbot.png',
  },
  {
    id: 'face-recognitionsearch',
    name: 'Face RecognitionSearch',
    category: 'AI Services',
    src: '/studio/icons/face-recognitionsearch.png',
  },
  {
    id: 'clova-facesign',
    name: 'CLOVA FaceSign',
    category: 'AI Services',
    src: '/studio/icons/clova-facesign.png',
  },
  {
    id: 'clova-nsml',
    name: 'CLOVA NSML',
    category: 'AI Services',
    src: '/studio/icons/clova-nsml.png',
  },
  {
    id: 'clova-carecall',
    name: 'CLOVA CareCall',
    category: 'AI Services',
    src: '/studio/icons/clova-carecall.png',
  },
  {
    id: 'clova-ocr',
    name: 'CLOVA OCR',
    category: 'AI Services',
    src: '/studio/icons/clova-ocr.png',
  },
  {
    id: 'clova-aicall',
    name: 'CLOVA AiCall',
    category: 'AI Services',
    src: '/studio/icons/clova-aicall.png',
  },
  {
    id: 'clova-aicallconnect',
    name: 'CLOVA AiCallConnect',
    category: 'AI Services',
    src: '/studio/icons/clova-aicallconnect.png',
  },
  {
    id: 'clova-speech',
    name: 'CLOVA Speech',
    category: 'AI Services',
    src: '/studio/icons/clova-speech.png',
  },
  {
    id: 'clova-dubbing',
    name: 'CLOVA Dubbing',
    category: 'AI Services',
    src: '/studio/icons/clova-dubbing.png',
  },
  {
    id: 'clova-nsml-v2',
    name: 'CLOVA NSML(v2)',
    category: 'AI Services',
    src: '/studio/icons/clova-nsml-v2.png',
  },
  {
    id: 'aitems',
    name: 'AiTEMS',
    category: 'AI Services',
    src: '/studio/icons/aitems.png',
  },
  {
    id: 'clova-ekyc',
    name: 'CLOVA eKYC',
    category: 'AI Services',
    src: '/studio/icons/clova-ekyc.png',
  },
  {
    id: 'clova-studio',
    name: 'CLOVA Studio',
    category: 'AI Services',
    src: '/studio/icons/clova-studio.png',
  },
  {
    id: 'clova-greeneye',
    name: 'CLOVA GreenEye',
    category: 'AI Services',
    src: '/studio/icons/clova-greeneye.png',
  },
  {
    id: 'clova-voice',
    name: 'Clova Voice',
    category: 'AI Services',
    src: '/studio/icons/clova-voice.png',
  },
  {
    id: 'clova-speech-recognition-csr',
    name: 'Clova Speech Recognition(CSR)',
    category: 'AI Services',
    src: '/studio/icons/clova-speech-recognition-csr.png',
  },
  {
    id: 'papago-translation',
    name: 'Papago Translation',
    category: 'AI Services',
    src: '/studio/icons/papago-translation.png',
  },
  {
    id: 'papago-image-translation',
    name: 'Papago Image Translation',
    category: 'AI Services',
    src: '/studio/icons/papago-image-translation.png',
  },
  {
    id: 'clova-clue',
    name: 'CLOVA CLUE',
    category: 'AI Services',
    src: '/studio/icons/clova-clue.png',
  },
  {
    id: 'simple-easynotification-service',
    name: 'Simple & EasyNotification Service',
    category: 'Application Services',
    src: '/studio/icons/simple-easynotification-service.png',
  },
  {
    id: 'api-gateway',
    name: 'API Gateway',
    category: 'Application Services',
    src: '/studio/icons/api-gateway.png',
  },
  {
    id: '5g-connect',
    name: '5G Connect',
    category: 'Application Services',
    src: '/studio/icons/5g-connect.png',
  },
  {
    id: 'cloud-outboundmailer',
    name: 'Cloud OutboundMailer',
    category: 'Application Services',
    src: '/studio/icons/cloud-outboundmailer.png',
  },
  {
    id: 'geolocation',
    name: 'GeoLocation',
    category: 'Application Services',
    src: '/studio/icons/geolocation.png',
  },
  {
    id: 'jeus',
    name: 'JEUS',
    category: 'Application Services',
    src: '/studio/icons/jeus.png',
  },
  {
    id: 'clara-parabricks',
    name: 'Clara Parabricks',
    category: 'Application Services',
    src: '/studio/icons/clara-parabricks.png',
  },
  {
    id: 'lena',
    name: 'LENA',
    category: 'Application Services',
    src: '/studio/icons/lena.png',
  },
  {
    id: 'pinpoint',
    name: 'Pinpoint',
    category: 'Application Services',
    src: '/studio/icons/pinpoint.png',
  },
  {
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'Application Services',
    src: '/studio/icons/rabbitmq.png',
  },
  {
    id: 'ncloud-maas',
    name: 'Ncloud MaaS',
    category: 'Application Services',
    src: '/studio/icons/ncloud-maas.png',
  },
  {
    id: 'simplerabbitmq-service',
    name: 'SimpleRabbitMQ Service',
    category: 'Application Services',
    src: '/studio/icons/simplerabbitmq-service.png',
  },
  {
    id: 'webtob',
    name: 'WebtoB',
    category: 'Application Services',
    src: '/studio/icons/webtob.png',
  },
  {
    id: 'maps',
    name: 'Maps',
    category: 'Application Services',
    src: '/studio/icons/maps.png',
  },
  {
    id: 'captcha',
    name: 'CAPTCHA',
    category: 'Application Services',
    src: '/studio/icons/captcha.png',
  },
  {
    id: 'nshorturl',
    name: 'nShortURL',
    category: 'Application Services',
    src: '/studio/icons/nshorturl.png',
  },
  {
    id: 'search-trend',
    name: 'Search Trend',
    category: 'Application Services',
    src: '/studio/icons/search-trend.png',
  },
  {
    id: 'cloud-datastreaming-service',
    name: 'Cloud DataStreaming Service',
    category: 'Big Data & Analytics',
    src: '/studio/icons/cloud-datastreaming-service.png',
  },
  {
    id: 'data-visualization',
    name: 'Data Visualization',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-visualization.png',
  },
  {
    id: 'cloud-hadoop',
    name: 'Cloud Hadoop',
    category: 'Big Data & Analytics',
    src: '/studio/icons/cloud-hadoop.png',
  },
  {
    id: 'data-catalog',
    name: 'Data Catalog',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-catalog.png',
  },
  {
    id: 'cloud-search',
    name: 'Cloud Search',
    category: 'Big Data & Analytics',
    src: '/studio/icons/cloud-search.png',
  },
  {
    id: 'data-analytics-service',
    name: 'Data Analytics Service',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-analytics-service.png',
  },
  {
    id: 'ai-forest',
    name: 'AI Forest',
    category: 'Big Data & Analytics',
    src: '/studio/icons/ai-forest.png',
  },
  {
    id: 'search-engineservice',
    name: 'Search EngineService',
    category: 'Big Data & Analytics',
    src: '/studio/icons/search-engineservice.png',
  },
  {
    id: 'heaan-homomorphicanalytics',
    name: 'HEaaN HomomorphicAnalytics',
    category: 'Big Data & Analytics',
    src: '/studio/icons/heaan-homomorphicanalytics.png',
  },
  {
    id: 'data-boxframe',
    name: 'Data BoxFrame',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-boxframe.png',
  },
  {
    id: 'cloud-data-box',
    name: 'Cloud Data Box',
    category: 'Big Data & Analytics',
    src: '/studio/icons/cloud-data-box.png',
  },
  {
    id: 'data-forest',
    name: 'Data Forest',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-forest.png',
  },
  {
    id: 'data-flow',
    name: 'Data Flow',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-flow.png',
  },
  {
    id: 'datafence',
    name: 'Datafence',
    category: 'Big Data & Analytics',
    src: '/studio/icons/datafence.png',
  },
  {
    id: 'data-query',
    name: 'Data Query',
    category: 'Big Data & Analytics',
    src: '/studio/icons/data-query.png',
  },
  {
    id: 'nimoro',
    name: 'NIMORO',
    category: 'Big Data & Analytics',
    src: '/studio/icons/nimoro.png',
  },
  {
    id: 'workplace-g',
    name: 'WORKPLACE g',
    category: 'Business Applications',
    src: '/studio/icons/workplace-g.png',
  },
  {
    id: 'workplace',
    name: 'WORKPLACE',
    category: 'Business Applications',
    src: '/studio/icons/workplace.png',
  },
  {
    id: 'wokrplace',
    name: 'Wokrplace',
    category: 'Business Applications',
    src: '/studio/icons/wokrplace.png',
  },
  {
    id: 'naver-works',
    name: 'NAVER WORKS',
    category: 'Business Applications',
    src: '/studio/icons/naver-works.png',
  },
  {
    id: 'rpa-service',
    name: 'RPA Service',
    category: 'Business Applications',
    src: '/studio/icons/rpa-service.png',
  },
  {
    id: 'ncloud-chat',
    name: 'Ncloud Chat',
    category: 'Business Applications',
    src: '/studio/icons/ncloud-chat.png',
  },
  {
    id: 'livecommerce-pot',
    name: 'LIVECOMMERCE POT',
    category: 'Business Applications',
    src: '/studio/icons/livecommerce-pot.png',
  },
  {
    id: 'storepot',
    name: 'StorePot',
    category: 'Business Applications',
    src: '/studio/icons/storepot.png',
  },
  {
    id: 'workbox',
    name: 'WORKBOX',
    category: 'Business Applications',
    src: '/studio/icons/workbox.png',
  },
  {
    id: 'marketpot',
    name: 'MARKETPOT',
    category: 'Business Applications',
    src: '/studio/icons/marketpot.png',
  },
  {
    id: 'cdn',
    name: 'CDN+',
    category: 'Content Delivery',
    src: '/studio/icons/cdn.png',
  },
  {
    id: 'global-cdn',
    name: 'Global CDN',
    category: 'Content Delivery',
    src: '/studio/icons/global-cdn.png',
  },
  {
    id: 'global-edge',
    name: 'Global Edge',
    category: 'Content Delivery',
    src: '/studio/icons/global-edge.png',
  },
  {
    id: 'sourceboard',
    name: 'SourceBoard',
    category: 'Developer Tools',
    src: '/studio/icons/sourceboard.png',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'Developer Tools',
    src: '/studio/icons/jenkins.png',
  },
  {
    id: 'sourcebuild',
    name: 'SourceBuild',
    category: 'Developer Tools',
    src: '/studio/icons/sourcebuild.png',
  },
  {
    id: 'sourcecommit',
    name: 'SourceCommit',
    category: 'Developer Tools',
    src: '/studio/icons/sourcecommit.png',
  },
  {
    id: 'sourcedeploy',
    name: 'SourceDeploy',
    category: 'Developer Tools',
    src: '/studio/icons/sourcedeploy.png',
  },
  {
    id: 'sourcepipeline',
    name: 'SourcePipeline',
    category: 'Developer Tools',
    src: '/studio/icons/sourcepipeline.png',
  },
  {
    id: 'neurocloud',
    name: 'Neurocloud',
    category: 'Hybrid & Private cloud',
    src: '/studio/icons/neurocloud.png',
  },
  {
    id: 'microcloud',
    name: 'Microcloud',
    category: 'Hybrid & Private cloud',
    src: '/studio/icons/microcloud.png',
  },
  {
    id: 'hybrid-cloudhosting',
    name: 'Hybrid CloudHosting',
    category: 'Hybrid & Private cloud',
    src: '/studio/icons/hybrid-cloudhosting.png',
  },
  {
    id: 'vmwareon-ncp',
    name: 'Vmwareon NCP',
    category: 'Hybrid & Private cloud',
    src: '/studio/icons/vmwareon-ncp.png',
  },
  {
    id: 'paas-ta-on-ncloud',
    name: 'PaaS-TA on Ncloud',
    category: 'Hybrid & Private cloud',
    src: '/studio/icons/paas-ta-on-ncloud.png',
  },
  {
    id: 'monitoring',
    name: 'Monitoring',
    category: 'Management & Governance',
    src: '/studio/icons/monitoring.png',
  },
  {
    id: 'network-trafficmonitoring',
    name: 'Network TrafficMonitoring',
    category: 'Management & Governance',
    src: '/studio/icons/network-trafficmonitoring.png',
  },
  {
    id: 'pinpoint-cloud',
    name: 'Pinpoint Cloud',
    category: 'Management & Governance',
    src: '/studio/icons/pinpoint-cloud.png',
  },
  {
    id: 'resourcemanager',
    name: 'ResourceManager',
    category: 'Management & Governance',
    src: '/studio/icons/resourcemanager.png',
  },
  {
    id: 'sub-account',
    name: 'Sub Account',
    category: 'Management & Governance',
    src: '/studio/icons/sub-account.png',
  },
  {
    id: 'web-service-monitoring-system',
    name: 'Web service Monitoring System',
    category: 'Management & Governance',
    src: '/studio/icons/web-service-monitoring-system.png',
  },
  {
    id: 'real-user-analytics-rua',
    name: 'Real User Analytics(RUA)',
    category: 'Management & Governance',
    src: '/studio/icons/real-user-analytics-rua.png',
  },
  {
    id: 'effective-log-search-analytics-elsa',
    name: 'Effective Log Search & Analytics(ELSA)',
    category: 'Management & Governance',
    src: '/studio/icons/effective-log-search-analytics-elsa.png',
  },
  {
    id: 'organization',
    name: 'Organization',
    category: 'Management & Governance',
    src: '/studio/icons/organization.png',
  },
  {
    id: 'api-workflow',
    name: 'API Workflow',
    category: 'Management & Governance',
    src: '/studio/icons/api-workflow.png',
  },
  {
    id: 'cloud-activity-tracer',
    name: 'Cloud Activity Tracer',
    category: 'Management & Governance',
    src: '/studio/icons/cloud-activity-tracer.png',
  },
  {
    id: 'cloud-advisor',
    name: 'Cloud Advisor',
    category: 'Management & Governance',
    src: '/studio/icons/cloud-advisor.png',
  },
  {
    id: 'cloud-insight',
    name: 'Cloud Insight',
    category: 'Management & Governance',
    src: '/studio/icons/cloud-insight.png',
  },
  {
    id: 'ncloud-tools-sdk',
    name: 'Ncloud Tools& SDK',
    category: 'Management & Governance',
    src: '/studio/icons/ncloud-tools-sdk.png',
  },
  {
    id: 'cloud-loganalytics',
    name: 'Cloud LogAnalytics',
    category: 'Management & Governance',
    src: '/studio/icons/cloud-loganalytics.png',
  },
  {
    id: 'ncloud-singlesign-on',
    name: 'Ncloud SingleSign-On',
    category: 'Management & Governance',
    src: '/studio/icons/ncloud-singlesign-on.png',
  },
  {
    id: 'cost-explorer',
    name: 'Cost Explorer',
    category: 'Management & Governance',
    src: '/studio/icons/cost-explorer.png',
  },
  {
    id: 'service-quota',
    name: 'Service Quota',
    category: 'Management & Governance',
    src: '/studio/icons/service-quota.png',
  },
  {
    id: 'live-station',
    name: 'Live Station',
    category: 'Media',
    src: '/studio/icons/live-station.png',
  },
  {
    id: 'live-transcoder',
    name: 'Live Transcoder',
    category: 'Media',
    src: '/studio/icons/live-transcoder.png',
  },
  {
    id: 'b2b-prism-live-studio',
    name: 'B2B PRISM Live Studio',
    category: 'Media',
    src: '/studio/icons/b2b-prism-live-studio.png',
  },
  {
    id: 'vod-transcoder',
    name: 'VOD Transcoder',
    category: 'Media',
    src: '/studio/icons/vod-transcoder.png',
  },
  {
    id: 'iot-videostream',
    name: 'IoT VideoStream',
    category: 'Media',
    src: '/studio/icons/iot-videostream.png',
  },
  {
    id: 'image-optimizer',
    name: 'Image Optimizer',
    category: 'Media',
    src: '/studio/icons/image-optimizer.png',
  },
  {
    id: 'contents-management-system',
    name: 'Contents Management System',
    category: 'Media',
    src: '/studio/icons/contents-management-system.png',
  },
  {
    id: 'media-connectcenter',
    name: 'Media ConnectCenter',
    category: 'Media',
    src: '/studio/icons/media-connectcenter.png',
  },
  {
    id: 'video-playerenhancement',
    name: 'Video PlayerEnhancement',
    category: 'Media',
    src: '/studio/icons/video-playerenhancement.png',
  },
  {
    id: 'vod-station',
    name: 'VOD Station',
    category: 'Media',
    src: '/studio/icons/vod-station.png',
  },
  {
    id: 'b2b-prism-live-studio-2',
    name: 'B2B PRISM Live Studio',
    category: 'Media',
    src: '/studio/icons/b2b-prism-live-studio-2.png',
  },
  {
    id: 'one-click-multi-drm',
    name: 'One Click Multi DRM',
    category: 'Media',
    src: '/studio/icons/one-click-multi-drm.png',
  },
  {
    id: 'global-latency-status',
    name: 'Global Latency Status',
    category: 'Global Infrastructure',
    src: '/studio/icons/global-latency-status.png',
  },
  {
    id: 'gamepot',
    name: 'Gamepot',
    category: 'Global Infrastructure',
    src: '/studio/icons/gamepot.png',
  },
  {
    id: 'gamereport',
    name: 'GameReport',
    category: 'Global Infrastructure',
    src: '/studio/icons/gamereport.png',
  },
  {
    id: 'mobius',
    name: 'Mobius',
    category: 'Global Infrastructure',
    src: '/studio/icons/mobius.png',
  },
  {
    id: 'global-region',
    name: 'Global Region',
    category: 'Global Infrastructure',
    src: '/studio/icons/global-region.png',
  },
  {
    id: 'game-chat',
    name: 'Game Chat',
    category: 'Global Infrastructure',
    src: '/studio/icons/game-chat.png',
  },
  {
    id: 'cloud-iot-core',
    name: 'Cloud IoT Core',
    category: 'Global Infrastructure',
    src: '/studio/icons/cloud-iot-core.png',
  },
  {
    id: 'iot-device-hub',
    name: 'IoT Device Hub',
    category: 'Global Infrastructure',
    src: '/studio/icons/iot-device-hub.png',
  },
  {
    id: 'iot-edge',
    name: 'IoT Edge',
    category: 'Global Infrastructure',
    src: '/studio/icons/iot-edge.png',
  },
  {
    id: 'public-finance-cloud',
    name: 'Public Finance Cloud',
    category: 'Global Infrastructure',
    src: '/studio/icons/public-finance-cloud.png',
  },
  {
    id: 'blockchain-service',
    name: 'Blockchain Service',
    category: 'Migration',
    src: '/studio/icons/blockchain-service.png',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    category: 'Migration',
    src: '/studio/icons/gaming.png',
  },
  {
    id: 'data-teleporter',
    name: 'Data Teleporter',
    category: 'Migration',
    src: '/studio/icons/data-teleporter.png',
  },
  {
    id: 'arc-eye',
    name: 'ARC eye',
    category: 'Migration',
    src: '/studio/icons/arc-eye.png',
  },
  {
    id: 'ai-naver-api',
    name: 'AI-NAVER-API',
    category: 'Others',
    src: '/studio/icons/ai-naver-api.png',
  },
  {
    id: 'public-ip',
    name: 'Public IP',
    category: 'Others',
    src: '/studio/icons/public-ip.png',
  },
  {
    id: 'solutions',
    name: 'Solutions',
    category: 'Others',
    src: '/studio/icons/solutions.png',
  },
  {
    id: 'smartwork',
    name: 'SMARTWORK',
    category: 'Others',
    src: '/studio/icons/smartwork.png',
  },
  {
    id: 'ai',
    name: 'AI',
    category: 'Others',
    src: '/studio/icons/ai.png',
  },
  {
    id: 'hybrid',
    name: 'Hybrid',
    category: 'Others',
    src: '/studio/icons/hybrid.png',
  },
  {
    id: 'finance',
    name: 'Finance',
    category: 'Others',
    src: '/studio/icons/finance.png',
  },
  {
    id: 'nic',
    name: 'NIC',
    category: 'Others',
    src: '/studio/icons/nic.png',
  },
  {
    id: 'router',
    name: 'Router',
    category: 'Others',
    src: '/studio/icons/router.png',
  },
  {
    id: 'vpg',
    name: 'VPG',
    category: 'Others',
    src: '/studio/icons/vpg.png',
  },
  {
    id: 'internet-gateway',
    name: 'Internet Gateway',
    category: 'Others',
    src: '/studio/icons/internet-gateway.png',
  },
  {
    id: 'on-premise-gateway',
    name: 'On Premise Gateway',
    category: 'Others',
    src: '/studio/icons/on-premise-gateway.png',
  },
  {
    id: 'mirror-resource',
    name: 'Mirror Resource',
    category: 'Others',
    src: '/studio/icons/mirror-resource.png',
  },
  {
    id: 'tmax',
    name: 'Tmax',
    category: 'Others',
    src: '/studio/icons/tmax.png',
  },
  {
    id: 'internet',
    name: 'Internet',
    category: 'Others',
    src: '/studio/icons/internet.png',
  },
];

export const ICON_CATEGORIES: readonly string[] = [
  'Compute',
  'Containers',
  'Storage',
  'Networking',
  'Database',
  'Security',
  'AI Services',
  'Application Services',
  'Big Data & Analytics',
  'Business Applications',
  'Content Delivery',
  'Developer Tools',
  'Hybrid & Private cloud',
  'Management & Governance',
  'Media',
  'Global Infrastructure',
  'Migration',
  'Others',
];

const BY_ID = new Map(ICONS.map((icon) => [icon.id, icon]));

export const getIcon = (id: string): StudioIcon | undefined => BY_ID.get(id);

/** 이름으로 아이콘을 찾는다. 같은 이름을 먼저, 없으면 이름에 포함된 것을 고른다. 없으면 빈 문자열. */
export function findIconId(query: string): string {
  const q = query.toLowerCase();
  const exact = ICONS.find((icon) => icon.name.toLowerCase() === q);
  return (
    (exact ?? ICONS.find((icon) => icon.name.toLowerCase().includes(q)))?.id ??
    ''
  );
}
